config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "foods#index"
  # root "articles#index"

  resources :foods, except: [:update]
  resources :recipes, except: [:update] do
    resources :recipe_foods, except: [:update]
  end
  resources :public_recipes, except: [:update]
  resources :general_shopping_lists, except: [:update]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   can :read, :all
    #   return unless user.admin?

    user ||= User.new
    return unless user.present?

    can(:manage, Food, user:)
    can(:manage, Recipe, user:)
    can :manage, RecipeFood do |food|
      food.recipe.user == user
    end

    can :read, :all

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true
  validates :price, presence: true
  validates :quantity, numericality: { only_integer: true }, comparison: { greater_than: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
  validates :description, presence: true, length: { minimum: 5 }
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe

  validates :quantity, presence: true, numericality: { only_integer: true }, comparison: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes, dependent: :destroy
  has_many :foods, dependent: :destroy

  validates :name, presence: true

  def admin?
    'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :remember_me)
    end
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.includes(:user)
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user = current_user
    if @food.save
      redirect_to root_path, notice: 'Food added successfully'
    else
      render :new, alert: 'Sorry an error occured. Please try again'
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to root_path, alert: 'Food deleted successfully'
  end

  private

  def food_params
    params.permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/general_shopping_lists_controller.rb
class GeneralShoppingListsController < ApplicationController
  def index
    @recipe_foods = RecipeFood.includes(:food, :recipe)
    @missing_ingredient = @recipe_foods.select { |ing| ing.quantity > ing.food.quantity }
    @missing_ing = @missing_ingredient.map do |c|
      {
        name: c.food.name,
        quantity: c.quantity - c.food.quantity,
        price: c.food.price * (c.quantity - c.food.quantity)
      }
    end
    @total_price = @missing_ing.map { |all_prices| all_prices[:price] }.sum
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @recipes = Recipe.includes(:user).where(public: true).order(created_at: :desc)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.new
    @food = Food.all
  end

  def create
    @recipe_foods = RecipeFood.new(recipe_foods_params)
    if @recipe_foods.save
      redirect_to recipe_path(params[:recipe_id])
    else
      render :new
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    redirect_to recipe_path(params[:recipe_id])
  end

  private

  def recipe_foods_params
    params.permit(:quantity, :food_id, :recipe_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    if @recipe.save
      redirect_to recipes_path, notice: 'Recipe created successfully'
    else
      render :new, alert: 'Sorry an error occured. Please try again'
    end
  end

  def show
    @recipes = Recipe.includes(:recipe_foods).find(params[:id])
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path, alert: 'Recipe delete successfully'
  end

  private

  def recipe_params
    params.permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/general_shopping_list_helper.rb
module GeneralShoppingListHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/foods/index.html.erb
<div class="foods_table">
<h2> Welcome to the Food Index </h2>

<%= link_to 'Add Food', new_food_path, class:"btn btn-outline-success mb-2" %>
  <table>
    <tr>
      <th>Foods</th>
      <th>Measurement unit</th>
      <th>Unit price</th>
      <th>Quantity</th>
      <th>Actions</th>
    </tr>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name%></td>
        <td><%= food.measurement_unit%></td>
        <td>$<%= food.price%></td>
        <td><%= food.quantity%></td>
          <% if can? :destroy, food %>
          <td><%= button_to 'Delete', food_path(food), method: :delete, class:"btn btn-outline-danger"%></td>
          <% else %>
          <td class="text-danger">No action</td>
          <% end %>
      </tr>
    <% end %>
  </table>
</div>

app/views/foods/new.html.erb
<div class="form__container">
  <h2>Add food form</h2>

  <%= form_with model: @foods , url: foods_path, data: {turbo: false} do |f|%>
    <% if @food.errors.any? %>
      <div class="alert alert-danger">
        <% @food.errors.full_messages.each do |message| %>
        <div><%= message %></div>
        <% end %>
      </div>
    <% end %>

      <div class="form_control">
        <%= f.label :name %><br />
        <%= f.text_field :name %>
      </div>
      <div class="form_control">
        <%= f.label :measurement_unit %><br />
        <%= f.select :measurement_unit, ['gram', 'kilogram', 'cup', 'tablespoon']%>
      </div>
      <div class="form_control">
        <%= f.label :price %><br />
        <%= f.text_field :price %>
      </div>
      <div class="form_control">
        <%= f.label :quantity %><br />
        <%= f.text_field :quantity %>
      </div>

      <%= f.submit "Submit", class:"btn btn-success" %>
  <% end %>

app/views/general_shopping_lists/index.html.erb
<div class="recipe_food">
<h2> Welcome to the General Shopping List Index </h2>

  <p>
    <span>Total amount of itmes to buy: <%= @missing_ingredient.count %> </span>
    <span>Total value of food needed: $<%= (@total_price).floor %></span>
  </p>
  <table>
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Price</th>
    </tr>

    <% @missing_ing.each do |recipe_food| %>
      <tr>
        <td><%= recipe_food[:name] %></td>
        <td><%= recipe_food[:quantity] %></td>
        <td>$<%= recipe_food[:price]%></td>
      </tr>
      <% end %>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render partial: "shared/navbar" %>
  <div class="flash_messages">
  <%= render partial: "shared/flash" %>
  </div>

    <main>
      <section class="parent__container">
        <%= yield %>
      </section>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>    
  </body>
</html>

app/views/public_recipes/index.html.erb
<div class="recipes__public">
<h2> Welcome to the Public Recipe Index </h2>

<% @recipes.each do |recipe| %>
  <div class="recipe_info">
   <div>
    <h3><%= link_to recipe.name, recipe_path(recipe.id) %></h3>
    <p>By: <%= recipe.user.name %> </p>
   </div>
  <div class="public_recipe_status">
  <p>Preparation time: <%= recipe.preparation_time%></p>
  <p>Cooking time: <%= recipe.cooking_time%></p>
  </div>
  </div>
  <% end %>
</div>

app/views/recipe_foods/new.html.erb
<div class="form__container">
<h2>Add Ingredient</h2>

<%= form_with model: @recipe_foods, url: recipe_recipe_foods_path do |f| %>
    <div class="form_control">
      <%= f.label :quantity %>
      <%= f.number_field :quantity %>
    </div>

    <div class="form_control">
    <%= f.select(:food_id, @food.map{|u| [u.name, u.id]}) %>
    </div>

    <div class="form_control">
    <%= f.hidden_field :recipe_id, value: @recipe_food.recipe_id %>
    </div>
    <%= f.submit "Submit", class:"btn btn-success" %>
    </div>

<% end %>

app/views/recipes/index.html.erb
<div class="recipes__container">
  <h2> Welcome to the Recipe Index </h2>

  <% @recipes.each do |recipe| %>
      <% if can? :destroy, recipe %>
    <div class="recipe_info">
      <div>
      <h3><%= link_to recipe.name, recipe_path(recipe.id) %></h3>
        <%= button_to 'Remove',  recipe_path(recipe), method: :delete, class:"btn btn-outline-danger" %>
      </div>
      <p class="recipe_steps"><%= recipe.description[0..100]...%></p>
    </div>
      <% end %>
    <% end %>
    <%= link_to 'Add New Recipe', new_recipe_path, class:"btn btn-outline-success ms-3" %>
</div>

app/views/recipes/new.html.erb
<div class="form__container">
<h2>Add new Recipe</h2>

<%= form_with model: @recipes, url: recipes_path do |f| %>

  <% if @recipe.errors.any? %>
    <div class="alert alert-danger">
    <% @recipe.errors.full_messages.each do |message| %>
    <div><%= message %></div>
    <% end %>
    </div>
  <% end %>
  
    <div class="form_control">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="form_control">
      <%= f.label :preparation_time %>
      <%= f.text_field :preparation_time %>
    </div>
    <div class="form_control">
      <%= f.label :cooking_time %>
      <%= f.text_field :cooking_time %>
    </div>
    <div class="form_control">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
    <div class="form_control, stay_logged">
      <%= f.label :public %>
      <%= f.check_box :public, value: "true" %>
    </div>

    <%= f.submit "Submit", class:"btn btn-success" %>
  </div>
<% end %>

app/views/recipes/show.html.erb
<div class="recipe__details">
<h2> Welcome to the Recipe Show </h2>

  <div class="status">
      <h2><%= @recipes.name %></h2>
    <div class="holder">
      <p>Preparation time: <%= @recipes.preparation_time %> </p>
      <p>Cooking time: <%=@recipes.cooking_time %></p>
    </div>
    <p class="recipe_steps"><%= @recipes.description%></p>

    <%if can? :manage, @recipes %>
      <div class="recipe__actions">
        <%= link_to 'Generate shopping list', general_shopping_lists_path, class:"btn btn-outline-success" %>
        <%= link_to 'Add ingredient',  new_recipe_recipe_food_path(@recipes.id), class:"btn btn-outline-success" %>
      </div>
      <hr>
      <% end %>

    <table>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Value</th>
        <th>Actions</th>
      </tr>
      <% @recipes.recipe_foods.each do |r_food| %>
        <tr>
          <% if can? :destroy, @recipes %>
          <td> <%= r_food.food.name %> </td>
          <td> <%= r_food.quantity %></td>
          <td> $<%= r_food.food.price%> </td>
          <td class="action">
          <span class="modify_btn">
          <%= button_to 'Modify'%>
          </span>
          <%= button_to ' Remove', recipe_recipe_food_path(@recipes.id, r_food.id), method: :delete, class:"btn btn-outline-danger" %>
          </td>
          <% end %>
        </tr>
        <% end %>
    </table>
  </div>
</div>

app/views/shared/_flash.html.erb
<% if flash[:notice]%>
  <div class="alert alert-success" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert]%>
  <div class="alert alert-danger" role="alert">
    <%= flash[:alert]%>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
  <nav class="navbar navbar-expand-lg bg-body-tertiary p-3 bg-dark" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to "RecipeBlog", root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class:"nav-link active", aria_current:"page" %>
        </li>
        <li class="nav-item">
        <%= link_to "Recipes", recipes_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Public Recipes", public_recipes_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "General Shopping List", general_shopping_lists_path, class:"nav-link" %>
        </li>
      </ul>
      <% if user_signed_in? %>
    <span class="nav-text text-light mx-3"><%= link_to current_user.name, edit_user_registration_path, class:"nav-link" %></span>
      <span>
          <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:"btn btn-light" %>
      <% end %>
      </span>

    </div>
  </div>
</nav>